name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:    
    - name: Clone repository
      uses: actions/checkout@v3      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
    - name: Create test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Execution Report
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit      
